# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload connector and sync documentation

on:
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
      - name: Install dependencies
        run: npm install -g anypoint-cli-v4

      - name: List env (validate anypoint cli and credentials)
        run: |
          anypoint-cli-v4 account:environment:list \
          --client_id ${{ secrets.CLIENT_ID }} \
          --client_secret ${{ secrets.CLIENT_SECRET }} \
          --organization ${{ secrets.ORG_ID }}


      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - uses: s4u/maven-settings-action@v2.3.0
        with:
          servers: |
            [{
                "id": "MyExchangeId",
                "username": "~~~Client~~~",
                "password": "${{ secrets.CLIENT_ID }}~?~${{ secrets.CLIENT_SECRET }}"
            }]

      - name: Deploy connector with Anypoint Maven Facade
        run: mvn -B deploy -DskipTests --file pom.xml --settings /home/runner/.m2/settings.xml

      - name: Extract GAV
        id: extract
        uses: andreacomo/maven-gav-extractor@v2

      - name: Upload connector documentation
        run: |
          anypoint-cli-v4 exchange:asset:page:upload \
          ${{ steps.extract.outputs.group-id }}/${{ steps.extract.outputs.artifact-id }}/${{ steps.extract.outputs.version }} home README.md \
          --client_id ${{ secrets.CLIENT_ID }} \
          --client_secret ${{ secrets.CLIENT_SECRET }} \
          --organization ${{ secrets.ORG_ID }}