name: Upload connector and sync documentation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: QuadCorps/quadcorps-tutorial/mulesoft/001-sync-extensions-docs/quadcorps-dummy-connector/.github/workflows/maven.yml
